site_name: golang 部分代码解析
pages:
    - 开始: index.md
    - net: net.md
    - net/url: url.md
    - net/http: http.md
    - requests: requests.md

theme:
  name: 'material'
markdown_extensions:
  - admonition
  - codehilite
